---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ansible"  # Update with your keypair name
      instance_type: t2.micro
      security_group: default
      region: us-east-1  # Write the region where you want to lunch
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-06b21ccaeff8cd686", name: "manage-node-1" } # Update AMI ID according to your account 
      - { image: "ami-0866a3c8686eaeeba", name: "manage-node-2" } # Update the AMI ID according to the region
      - { image: "ami-0866a3c8686eaeeba", name: "manage-node-3" }
